require("ninghan.plugins-setup")

require("ninghan.core.options")
require("ninghan.core.colorscheme")
require("ninghan.core.keymaps")

require("ninghan.plugins.nvim-tree")
require("ninghan.plugins.lualine")
require("ninghan.plugins.telescope")
require("ninghan.plugins.nvim-cmp")
require("ninghan.plugins.lsp.mason")
require("ninghan.plugins.lsp.lspsaga")
require("ninghan.plugins.lsp.lspconfig")
require("ninghan.plugins.lsp.null-ls")
require("ninghan.plugins.autopairs")
require("ninghan.plugins.gitsigns")
require("ninghan.plugins.glow")
require("ninghan.plugins.treesitter")
require("ninghan.plugins.nvim-transparent")
require("ninghan.plugins.comment")
